# kubetpl:syntax:$

apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mysql-snapshot-$NAMESPACE-$WP_NUMBER-$RANDOM_UUID
  namespace: $NAMESPACE
  annotations:
    portworx/snapshot-type: local
    portworx.selector/group: $SNAP_GROUP
spec:
  persistentVolumeClaimName: mysql-pvc