# kubetpl:syntax:$

apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mysql-snapshot-$NAMESPACE-$WP_NUMBER-$RANDOM_UUID
  namespace: $NAMESPACE
spec:
  persistentVolumeClaimName: mysql-pvc-$NAMESPACE-$WP_NUMBER